http:
  routers:
    router0:
      rule: "HostHeader(`a238c7319fdb042beacd861c3b3066dc-1540058085.us-east-1.elb.amazonaws.com`) && PathPrefix(`/`)"
      service: "service-foo"
    router-start:
      rule: "HostHeader(`*`)"
      service: "service-start"
      priority: -65535

  services:
    service-start:
      loadBalancer:
        servers:
        - url: "http://nginx/"
    service-foo:
      loadBalancer:
        servers:
        - url: "http://httpbin/"
