http:
  routers:
    router0:
      rule: "PathPrefix(`/`)"
      service: "service-foo"
    router-start:
      rule: "Host(`*`)"
      service: "service-start"
      priority: -65535

  services:
    service-start:
      loadBalancer:
        servers:
        - url: "http://nginx/"
    service-foo:
      loadBalancer:
        servers:
        - url: "http://httpbin/"
