http:
  routers:
    router-catchall:
      rule: "HostRegexp(`{catchall:.*}`)"
      service: "service-httpbin"
      priority: 1

  services:
    service-whoami:
      loadBalancer:
        servers:
        - url: "http://nginx/"
    service-httpbin:
      loadBalancer:
        servers:
        - url: "http://httpbin/"
